[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2"
reqwest = { version = "0.12.5", features = ["wasm"] }
